services:

  postgres:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    volumes:
      - polls_pg_data:/bitnami/postgresql

  api:
    container_name: api
    build:
      context: "./"
      dockerfile: Dockerfile

    volumes:
      - "/app"
    ports:
      - 3001:3001
volumes:
  polls_pg_data:
