version: '3.7'

services:
  postgres:
    image: 'bitnami/postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data:
